import Head from 'next/head'
import Image from 'next/image'
import code from './code.png'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>FundMi</h1>
            <ul className='flex items-center'>
              <button className='bg-gradient-to-r from-cyan-500 to-teal-500 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 text-white px-4 py-2 rounded-md ml-8'>Connect</button>
            </ul>
          </nav>
          <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Lets Fund Your Project</h2>
              <h3 className='text-2xl py-2 md:text-3xl'>Decentralized Crowdfunding</h3>
              <p className='text-md py-5 leading-8 text-gray-800 rounded-b md:text-xl max-w-xl mx-auto dark:bg-slate-500'>
                FundMi is a Web3 application which helps to raise funds using Matic. It is
                a first step towards a decentralized future. No need to worry about siphoning away of funds.
              </p>
              <button className='bg-gradient-to-r from-cyan-500 to-teal-500 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 text-white px-4 py-2 rounded-md ml-8'>Get started</button>
          </div>
          <div className='text-center'>
            <h3 className='text-5xl py-12 text-teal-600 font-medium md:text-6xl'>Available Projects</h3>
            <div className='lg:flex gap-10'>
            <div className="text-center shadow-2xl p-10 ml-10 rounded-xl my-10  dark:bg-white">
              {/* <img src={code} className='object-center'/> */}
              <div>
              <Image src={code} 
                width={100} 
                height={100} 
              />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Shiki Wrap: Heaven on Earth</h3>
              <p className='py-2'>
              Shiki Wrap: Heaven on Earth will bring our reversible, 
              reusable gift bags to life while elevating the work of artists
              José Francisco Salgado and Michelle Woo.
              </p>
              <div className='p-4'>
              <button className='bg-gradient-to-r from-cyan-500 to-teal-500 
              transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 
              text-white px-4 py-2 rounded-md ml-8'>Read more</button>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 ml-10 rounded-xl my-10  dark:bg-white">
              {/* <img src={code} className='object-center'/> */}
              <div>
              <Image src={code} 
                width={100} 
                height={100} 
              />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Shiki Wrap: Heaven on Earth</h3>
              <p className='py-2'>
              Shiki Wrap: Heaven on Earth will bring our reversible, 
              reusable gift bags to life while elevating the work of artists
              José Francisco Salgado and Michelle Woo.
              </p>
              <div className='p-4'>
              <button className='bg-gradient-to-r from-cyan-500 to-teal-500 
              transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 
              text-white px-4 py-2 rounded-md ml-8'>Read more</button>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 ml-10 rounded-xl my-10  dark:bg-white">
              {/* <img src={code} className='object-center'/> */}
              <div>
              <Image src={code} 
                width={100} 
                height={100} 
              />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Shiki Wrap: Heaven on Earth</h3>
              <p className='py-2'>
              Shiki Wrap: Heaven on Earth will bring our reversible, 
              reusable gift bags to life while elevating the work of artists
              José Francisco Salgado and Michelle Woo.
              </p>
              <div className='p-4'>
              <button className='bg-gradient-to-r from-cyan-500 to-teal-500 
              transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 
              text-white px-4 py-2 rounded-md ml-8'>Read more</button>
              </div>
            </div>           
          </div>
          </div>
        </section>
      </main>
    </>
  )
}
